import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased relative`}>
        <div className="lg:hidden fixed inset-0 bg-black/5 backdrop-blur-sm z-50 flex items-center justify-center">
          <div className="bg-yellow-400/90 text-black px-6 py-3 rounded-full font-bold text-lg">
            Coming Soon
          </div>
        </div>
        
        <div className="hidden lg:block">
          {children}
        </div>
      </body>
    </html>
  );
}